### ISSUE TITLE
herokuでのエラー

### ISSUE THREAD

**Issue by yukukotani** [kanreisa/reichat#9]
Variablesを全て初期値でHerokuにデプロイすると、Appliaction Errorが発生します。

log:
<addr>2016-09-05T04:49:59.031844+00:00 app[web.1]: npm ERR!     npm bugs reichat
2016-09-05T04:49:59.033915+00:00 app[web.1]: npm ERR!     npm owner ls reichat
2016-09-05T04:49:59.033915+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-05T04:49:59.041035+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-09-05T04:50:09.988122+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=gentle-island-78802.herokuapp.com request_id=349fdf30-f5c6-4cc3-bbe3-de918348c74f fwd="123.216.201.48" dyno= connect= service= status=503 bytes=
2016-09-05T04:50:24.939113+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=gentle-island-78802.herokuapp.com request_id=f6705872-e7e0-4d03-b033-45958ea324ba fwd="123.216.201.48" dyno= connect= service= status=503 bytes=
2016-09-05T04:50:25.552358+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-island-78802.herokuapp.com request_id=3d7d027e-e5ac-4066-b018-eb641ab3356d fwd="123.216.201.48" dyno= connect= service= status=503 bytes=
2016-09-05T04:50:32.832813+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=gentle-island-78802.herokuapp.com request_id=cbb0ece6-e613-41ef-9dda-b6e998f6d4fd fwd="123.216.201.48" dyno= connect= service= status=503 bytes=
2016-09-05T04:50:33.360943+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-island-78802.herokuapp.com request_id=425e1b90-36c6-4afa-b897-34691a8e9ee7 fwd="123.216.201.48" dyno= connect= service= status=503 bytes=</addr>

**Comment by fightwen** [comment]
I used heroku to deploy reichat , but it has some error message. How should I fix it? Thanks!

2016-09-11T11:52:49.509004+00:00 app[web.1]: > reichat@0.0.34 start /app
2016-09-11T11:52:49.509005+00:00 app[web.1]: 
2016-09-11T11:52:49.964013+00:00 app[web.1]: /app/node_modules/png-async/lib/index.js:28
2016-09-11T11:52:49.964025+00:00 app[web.1]:     constructor(option = {}) {
2016-09-11T11:52:49.964026+00:00 app[web.1]:                        ^
2016-09-11T11:52:49.964027+00:00 app[web.1]: 
2016-09-11T11:52:49.964028+00:00 app[web.1]: SyntaxError: Unexpected token =
2016-09-11T11:52:49.964029+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-09-11T11:52:49.964030+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-09-11T11:52:49.964030+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-09-11T11:52:49.964031+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-09-11T11:52:49.964032+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-09-11T11:52:49.964032+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-09-11T11:52:49.990403+00:00 app[web.1]: npm ERR! reichat@0.0.34 start: `./bin/reichat.js`
2016-09-11T11:52:49.990641+00:00 app[web.1]: npm ERR! Exit status 1
2016-09-11T11:52:49.991207+00:00 app[web.1]: npm ERR! Failed at the reichat@0.0.34 start script './bin/reichat.js'.
2016-09-11T11:52:49.991485+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-09-11T11:52:49.991728+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the reichat package,
2016-09-11T11:52:49.991994+00:00 app[web.1]: npm ERR! not with npm itself.
2016-09-11T11:52:49.992507+00:00 app[web.1]: npm ERR!     ./bin/reichat.js
2016-09-11T11:52:49.992784+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-09-11T11:52:49.993022+00:00 app[web.1]: npm ERR!     npm bugs reichat
2016-09-11T11:52:49.993531+00:00 app[web.1]: npm ERR!     npm owner ls reichat
2016-09-11T11:52:49.993805+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-09-11T11:52:49.999385+00:00 app[web.1]: 
2016-09-11T11:52:49.999887+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-09-11T11:52:50.140414+00:00 heroku[web.1]: Process exited with status 1
2016-09-11T11:52:50.135273+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-11T11:57:29.663243+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testpaintchat.herokuapp.com request_id=493d466a-a486-4480-96dc-3583c19520c0 fwd="114.45.62.28" dyno= connect= service= status=503 bytes=
2016-09-11T11:57:30.744860+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testpaintchat.herokuapp.com request_id=c903082c-a38f-42da-b1d6-dc880d3340b1 fwd="114.45.62.28" dyno= connect= service= status=503 bytes=

**Comment by kanreisa** [comment]
thank you @fightwen , that log is great help to resolve problem.
I fixed on reichat@0.0.35.
@Mon-chi @fightwen , cloud you try again?

**Comment by yukukotani** [comment]
The problem has been resolved on my environment. Thanks!

**Comment by fightwen** [comment]
Ok! No problem.Thanks a lot.
I like it more and more ^_^
Hope that  Reichat will has  more  features in the future.
Great!! ^o^
